const dollFetterTypesJSON = 
`
[
	{
	"id": 0,
	"targetGroup":"Doll",
	"name": "Hateful",
	"relation": "of",
	"flavorText": "You feel fierce hatred for her. The reason doesn't matter. Everything she does annoys you. How frustrating!",
	"flavorImage": "Hateful.png",
	"madName": "Open Hostility",
	"madRelation": "towards",
	"madEffect": "During combat, Attacks you make that fail to hit an enemy will hit the target of the Fetter instead (if they are within range.) The target may choose where to take the damage.",
	"madFlavorText": "Wouldn't it be nice if she just fell to pieces?",
	"madFlavorImage": "OpenHostility.png"
	},
	{
	"id": 1,
	"targetGroup":"Doll",
	"name": "Possessive",
	"relation": "of",
	"flavorText": "You want to possess her. To make her your own and not let anyone have her. One could call it love, but it's more wicked than that.",
	"flavorImage": "Possessive.png",
	"madName": "Possessive Action",
	"madRelation": "towards",
	"madEffect": "At the beginning and end of combat, choose a Part of the target's to deal 1 damage to.",
	"madFlavorText": "Your eyes... how beautiful they truly are.",
	"madFlavorImage": "PossessiveAction.png"
	},
	{
	"id": 2,
	"targetGroup":"Doll",
	"name": "Dependent",
	"relation": "on",
	"flavorText": "The target is someone you just can't live without. If they aren't there, you are nothing.",
	"flavorImage": "Dependent.png",
	"madName": "Infantile Relapse",
	"madRelation": "",
	"madEffect": "Your Maximum Action Points decrease by 2.",
	"madFlavorText": "Don't leave me alone... waaah, I'm scared!",
	"madFlavorImage": "InfantileRelapse.png"
	},
	{
	"id": 3,
	"targetGroup":"Doll",
	"name": "Attached",
	"relation": "to",
	"flavorText": "You want to stay by her side. To always be wherever she is. You'll never, never be apart.",
	"flavorImage": "Attached.png",
	"madName": "Relentless Observation",
	"madRelation": "of",
	"madEffect": "At the beginning and end of combat, the target receives a Madness Point upon her Fetter towards you (if she is already in a Broken state, this has no effect.)",
	"madFlavorText": "I'll always be watching you. Heheheh...",
	"madFlavorImage": "RelentlessObservation.png"
	},
	{
	"id": 4,
	"targetGroup":"Doll",
	"name": "Devoted",
	"relation": "to",
	"flavorText": "You're in love with the target so much it hurts. You don't want her to hate you. You can't take your eyes off her. It's embarrassing...",
	"flavorImage": "Devoted.png",
	"madName": "Self-Harming Action",
	"madRelation": "",
	"madEffect": "At the beginning and end of combat, damage one of your own Parts.",
	"madFlavorText": "If she won't look at me, I don't need this body...",
	"madFlavorImage": "SelfHarmingAction.png"
	},
	{
	"id": 5,
	"targetGroup":"Doll",
	"name": "Rival",
	"relation": "of",
	"flavorText": "You won't lose to her. It's not that you hate her. You just don't want to lose to her. You're rivals.",
	"flavorImage": "Rival.png",
	"madName": "Excessive Competition",
	"madRelation": "",
	"madEffect": "At the beginning and end of combat, receive a Madness Point upon a Fetter of your choice (if you are already in a Broken state, this has no effect.)",
	"madFlavorText": "Just try and do better than me... if you can. Come on, try!",
	"madFlavorImage": "ExcessiveCompetition.png"
	},
	{
	"id": 6,
	"targetGroup":"Doll",
	"name": "Friendly",
	"relation": "towards",
	"flavorText": "She's a friend and an important companion. As her dear friend, there's nothing you wouldn't do for her.",
	"flavorImage": "Friendly.png",
	"madName": "Inordinate Empathy",
	"madRelation": "towards",
	"madEffect": "At the end of a Session, if the target of the Fetter has more damaged Parts than you do, take damage to Parts of your choice until you have the same number of damaged Parts.",
	"madFlavorText": "Your legs are gone? Don't worry, I'll get rid of mine too.",
	"madFlavorImage": "InordinateEmpathy.png"
	},
	{
	"id": 7,
	"targetGroup":"Doll",
	"name": "Protective",
	"relation": "of",
	"flavorText": "That girl's weak. She needs you to protect her. To help her. She can't do anything on her own.",
	"flavorImage": "Protective.png",
	"madName": "Constant Contact",
	"madRelation": "with",
	"madEffect": "During combat, if you are in a different area from the target of the Fetter, you may not use Maneuvers that have an effect other than Movement. In addition, you may not use Movement Maneuvers upon targets other than yourself or the target of the Fetter.",
	"madFlavorText": "Don't take one step away. Because I've got to protect you!",
	"madFlavorImage": "ConstantContact.png"
	},
	{
	"id": 8,
	"targetGroup":"Doll",
	"name": "Idolatrous",
	"relation": "of",
	"flavorText": "You want to be just like her. She's everything that you long to be... that you wish you could be.",
	"flavorImage": "Idolatrous.png",
	"madName": "Imposter Delusion",
	"madRelation": "of",
	"madEffect": "During combat, if you are in the same area from the target of the Fetter, you may not use Maneuvers that have an effect other than Movement. In addition, you may not use Movement Maneuvers upon targets other than yourself or the target of the Fetter.",
	"madFlavorText": "Liar! My beloved sister would never say that! You're a fake! I won't be fooled!",
	"madFlavorImage": "ImposterDelusion.png"
	},
	{
	"id": 9,
	"targetGroup":"Doll",
	"name": "Trusting",
	"relation": "of",
	"flavorText": "Your heart is as one with her. You can trust her with everything. Whenever she's by your side, you can feel at ease.",
	"flavorImage": "Trusting.png",
	"madName": "Universal Suspicion",
	"madRelation": "",
	"madEffect": "All of your Sisters other than you receive a modifier of -1 to their Maximum Action Points.",
	"madFlavorText": "...You go first. I know you mean to shoot me in the back. I won't let you.",
	"madFlavorImage": "UniversalSuspicion.png"
	},
	{
	"id": 10,
	"targetGroup":"Savant",
	"name": "Fearful",
	"relation": "of",
	"flavorText": "You don't want to remember her. You don't want to think of her. To you, she is a font of despair.",
	"flavorImage": "Fearful.png",
	"madName": "Reality Rejection",
	"madRelation": "",
	"madEffect": "All Action and Madness Checks you make receive a modifier of -1.",
	"madFlavorText": "Th-that's an phantom, a fake, there's nothing there... nothing to worry about... nothing...",
	"madFlavorImage": "RealityRejection.png"
	},
	{
	"id": 11,
	"targetGroup":"Savant",
	"name": "Subservient",
	"relation": "towards",
	"flavorText": "Your obedience to her is engraved deep into your heart. At times, it still torments you with indecision.",
	"flavorImage": "Subservient.png",
	"madName": "Justified Betrayal",
	"madRelation": "",
	"madEffect": "During the Battle Phase, all of your failures on Attack Checks become Critical Failures.",
	"madFlavorText": "I'm sorry... I understand you... but, even so, I cannot disobey that person.",
	"madFlavorImage": "JustifiedBetrayal.png"
	},
	{
	"id": 12,
	"targetGroup":"Savant",
	"name": "Unease",
	"relation": "about",
	"flavorText": "You've felt uneasy about that person from the start. As if she might have some terrifying secret. That's why...",
	"flavorImage": "Unease.png",
	"madName": "Suspicious Behavior",
	"madRelation": "",
	"madEffect": "Your Maximum Action Points decrease by 2.",
	"madFlavorText": "O-o-o-o-oh, is that so... y-you must be mistaken!",
	"madFlavorImage": "SuspiciousBehavior.png"
	},
	{
	"id": 13,
	"targetGroup":"Savant",
	"name": "Pity",
	"relation": "for",
	"flavorText": "You don't want to understand her, but you do. You know you should hate her, but you don't. You just feel sorry for her.",
	"flavorImage": "Pity.png",
	"madName": "Ubiquitous Sympathy",
	"madRelation": "",
	"madEffect": "You receive a modifier of -1 to Attack Checks against Savants.",
	"madFlavorText": "There wasn't any other way... must I do this to you too?...",
	"madFlavorImage": "UbiquitousSympathy.png"
	},
	{
	"id": 14,
	"targetGroup":"Savant",
	"name": "Love-Hate",
	"relation": "for",
	"flavorText": "She's an enemy that you should hate, but you can't hate her. How could you ever not realize there's good things about her too?",
	"flavorImage": "LoveHate.png",
	"madName": "Wicked Affection",
	"madRelation": "",
	"madEffect": "For each Critical Success you roll on an Action Check or Madness Check, do (the result of the check - 10) Damage to your own Parts of your choice.",
	"madFlavorText": "What should I do... I love you, but I've no choice but to fight you!",
	"madFlavorImage": "WickedAffection.png"
	},
	{
	"id": 15,
	"targetGroup":"Savant",
	"name": "Regret",
	"relation": "for",
	"flavorText": "It's because of you that she's become like this. You can't help but regret that.",
	"flavorImage": "Regret.png",
	"madName": "Just Desserts",
	"madRelation": "",
	"madEffect": "When you roll a failure on an Attack Check, do the damage of the attack to a Location of your choice.",
	"madFlavorText": "I'm sorry, I'm sorry, I'm sorry! If only... if only I weren't here, everyone would be fine!",
	"madFlavorImage": "JustDesserts.png"
	},
	{
	"id": 16,
	"targetGroup":"Savant",
	"name": "Disdain",
	"relation": "for",
	"flavorText": "Just what value does she have? You'd never associate with the likes of her by choice.",
	"flavorImage": "Disdain.png",
	"madName": "Willful Blindness",
	"madRelation": "",
	"madEffect": "Enemies in the same Area as you gain a modifier of +1 to Attack Checks made against you.",
	"madFlavorText": "Hey, this isn't the time to be tripping over everything! Let's go!",
	"madFlavorImage": "WillfulBlindness.png"
	},
	{
	"id": 17,
	"targetGroup":"Savant",
	"name": "Anger",
	"relation": "towards",
	"flavorText": "Your heart is like a maelstrom of rage towards her. You can't think of anything but destroying her.",
	"flavorImage": "Anger.png",
	"madName": "Unchecked Emotion",
	"madRelation": "",
	"madEffect": "All Action and Madness Checks you make receive a modifier of -1.",
	"madFlavorText": "...!!!",
	"madFlavorImage": "UncheckedEmotion.png"
	},
	{
	"id": 18,
	"targetGroup":"Savant",
	"name": "Grudge",
	"relation": "towards",
	"flavorText": "You'll never forgive her. You'll never forget her. Even if you become junk, you'll crawl back for her.",
	"flavorImage": "Anger.png",
	"madName": "Eternal Malice",
	"madRelation": "towards",
	"madEffect": "You cannot escape from Battle. You must pay an additional AP to use Maneuvers on any target other than yourself or the target of this Fetter.",
	"madFlavorText": "Did you think a trifling thing like dying would make me forgive you?!",
	"madFlavorImage": "EternalMalice.png"
	},
	{
	"id": 19,
	"targetGroup":"Savant",
	"name": "Hatred",
	"relation": "of",
	"flavorText": "Hatred as cold as steel pierces the very core of your being. As long as she exists in this world, you will continue to embrace it.",
	"flavorImage": "Hatred.png",
	"madName": "Existence Erasure",
	"madRelation": "",
	"madEffect": "When this Fetter enters a state of Madness, choose one of your Sisters and destroy two of their Parts.",
	"madFlavorText": "This hand stinks of her... I'll be getting rid of it for you.",
	"madFlavorImage": "ExistanceErasure.png"
	},
	{
	"id": 20,
	"targetGroup":"Neutral",
	"name": "Evasive",
	"relation": "towards",
	"flavorText": "She disgusts you. You don't want to touch her. You don't want to be near her. You can't even look at her.",
	"flavorImage": "Evasive.png",
	"madName": "Deliberate Isolation",
	"madRelation": "from",
	"madEffect": "During combat, when you are in the same Area as the target of this Fetter or a Savant, you may not use Maneuvers that have an effect other than Movement. In addition, you may not use Movement Maneuvers upon targets other than yourself or the triggers of this effect.",
	"madFlavorText": "D-don't come near me! Don't come closer! Don't get any closer!",
	"madFlavorImage": "DeliberateIsolation.png"
	},
	{
	"id": 21,
	"targetGroup":"Neutral",
	"name": "Jealous",
	"relation": "of",
	"flavorText": "This body of yours is in such an awful state, so why is hers... why is hers?...",
	"flavorImage": "Jealous.png",
	"madName": "Sororal Disharmony",
	"madRelation": "",
	"madEffect": "All of your Sisters receive a modifier of -1 to Action Checks.",
	"madFlavorText": "If only... if only the rest of you were suffering just like me...",
	"madFlavorImage": "SororalDisharmony.png"
	},
	{
	"id": 22,
	"targetGroup":"Neutral",
	"name": "Dependent",
	"relation": "on",
	"flavorText": "You can't imagine herself without her. You can't be apart. You don't want to be apart. Never ever...",
	"flavorImage": "Dependent.png",
	"madName": "Infantile Relapse",
	"madRelation": "",
	"madEffect": "Your Maximum Action Points decrease by 2.",
	"madFlavorText": "Stay here with me... please, if you don't...!",
	"madFlavorImage": "InfantileRelapse.png"
	},
	{
	"id": 23,
	"targetGroup":"Neutral",
	"name": "Pity",
	"relation": "for",
	"flavorText": "Why is it that she's the only one who had to go through that suffering? Did she do anything to deserve it?",
	"flavorImage": "Pity.png",
	"madName": "Ubiquitous Sympathy",
	"madRelation": "",
	"madEffect": "You receive a modifier of -1 to Attack Checks against Savants.",
	"madFlavorText": "Stop it! Why... why must we do this?!",
	"madFlavorImage": "UbiquitousSympathy.png"
	},
	{
	"id": 24,
	"targetGroup":"Neutral",
	"name": "Grateful",
	"relation": "towards",
	"flavorText": "You're simply grateful to her. It's thanks to her that your body and mind are here right now... even if it's not much of a body.",
	"flavorImage": "Grateful.png",
	"madName": "Pathological Renumeration",
	"madRelation": "",
	"madEffect": "When this Fetter enters a state of Madness, destroy two of your Basic Parts. If none remain, destroy one of your lowest level Reinforcement Parts.",
	"madFlavorText": "These eyes are the least I can give you. It's thanks to you they were able to see so many things.",
	"madFlavorImage": "PathologicalRenumeration.png"
	},
	{
	"id": 25,
	"targetGroup":"Neutral",
	"name": "Regret",
	"relation": "for",
	"flavorText": "That she's become like this is your own fault. Even now, that truth pierces through your heart like a thorn.",
	"flavorImage": "Regret.png",
	"madName": "Just Desserts",
	"madRelation": "",
	"madEffect": "When you roll a failure on an Attack Check, do the damage of the attack to a Location of your choice.",
	"madFlavorText": "That's right. It's my fault. It's my fault that you all became like this...!",
	"madFlavorImage": "JustDesserts.png"
	},
	{
	"id": 26,
	"targetGroup":"Neutral",
	"name": "Faith",
	"relation": "in",
	"flavorText": "You're certain she can do anything for you. That knowledge gives you hope. She can. There's no doubt about it. She can.",
	"flavorImage": "Faith.png",
	"madName": "Shattered Hope",
	"madRelation": "",
	"madEffect": "Whenever you use a Madness Point to reroll a die, you receive a penalty of -1 to that die roll. (This penalty is cumulative.)",
	"madFlavorText": "I was counting on you! You piece of trash! You useless corpse!",
	"madFlavorImage": "ShatteredHope.png"
	},
	{
	"id": 27,
	"targetGroup":"Neutral",
	"name": "Guardian",
	"relation": "of",
	"flavorText": "It's not just because she's your Sister that you must protect her. There's something more than that...",
	"flavorImage": "Guardian.png",
	"madName": "Negation Delirium",
	"madRelation": "",
	"madEffect": "You cannot target Legions with Maneuvers.",
	"madFlavorText": "You're all still alive... I'm glad... I'm so glad...",
	"madFlavorImage": "ShatteredHope.png"
	},
	{
	"id": 28,
	"targetGroup":"Neutral",
	"name": "Reverent",
	"relation": "of",
	"flavorText": "You're different from her, that's for certain. But that's why you can recognize how amazing she is.",
	"flavorImage": "Reverent.png",
	"madName": "Solitary Deification",
	"madRelation": "of",
	"madEffect": "You cannot target your other Sisters with Maneuvers.",
	"madFlavorText": "You're the only one I need, Onee-sama. No one else has a place in my heart",
	"madFlavorImage": "ShatteredHope.png"
	},
	{
	"id": 29,
	"targetGroup":"Neutral",
	"name": "Trusting",
	"relation": "of",
	"flavorText": "From the bottom of your heart, you can trust her. In this ruined world, she's the only person you can believe in.",
	"flavorImage": "Trusting.png",
	"madName": "Universal Suspicion",
	"madRelation": "",
	"madEffect": "All of your Sisters other than you receive a modifier of -1 to their Maximum Action Points.",
	"madFlavorText": "...You're my enemy too, aren't you? I'm sure of it!",
	"madFlavorImage": "UniversalSuspicion.png"
	}
]
`;